Todo_ajson/urls.py
from django.contrib import admin
from django.urls import path,include
from ajson import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ajson/",include('ajson.urls')),
    path('',views.viewdata, name='viewdata')
]

ajson/urls.py
from django.urls import path

from . import views

app_name = 'ajson'

urlpatterns = [
    path("getdata",views.getdata,name='getdata'),
    path("form-create",views.create, name='create')
]

ajson/models.py
import abc
from django.db import models

class Profile(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    about = models.CharField(max_length=500)
    date_added = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-date_added']

ajson/views.py
from django.shortcuts import render, redirect,HttpResponse
from .models import Profile
from django.http import JsonResponse

def viewdata(request):
    return render(request,'ajson/index.html')

def getdata(request):
    profiles = Profile.objects.all()
    context = {"profiles":list(profiles.values())}
    return JsonResponse(context)

def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        about = request.POST.get('about')
        data = Profile(name=name,email=email,about=about)
        data.save()
        return HttpResponse("données sauvegardées")
    
    return render(request,'ajson/form.html')

ajson/templates/ajson/form.html
{% extends 'base.html' %}


{% block style %}
    <style>
        button {
            color: brown;
        }
    </style>

{% endblock style %}
    
{% block content %}
<h1>Remplir le formulaire</h1>
    <form id="post-form">
        <p><label for="username">Name </label> <input type="text" id="username" name="name"></p>
        <p><label for="username">Email </label> <input type="email" id="email" name="email"></p>
        <p><label for="username">A propos de </label> <input type="text" id="about" name="about"></p>
        {% csrf_token %}
        <p><button type="submit">Envoyer</button></p>
    </form>

{% endblock content %}


{% block script %}
 <script>
    $(document).on('submit','#post-form',(e)=>{
        e.preventDefault;
        $.ajax({
            type:'POST',
            url:"{% url 'ajson:create' %}",
            data:{
                name:$('#username').val(),
                email:$('#email').val(),
                about:$('#about').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success:()=>{
                alert("données enregistrées")
            }
        })

    })
 </script>   
 
{% endblock script %}
    
    

ajson/templates/ajson/index.html
{% extends 'base.html' %}

{% block style %}
    <style>
        h1{
            text-align: center;
        }
        ul {
            list-style: none;
        }
    </style>    

{% endblock style %}
    

{% block content %}
<h1>Liste des noms</h1>
<ul id="name-data">
    
        
</ul>  
{% endblock content %}


{% block script %}

<script>
    $(document).ready(()=>{
        setInterval(()=>{
            $.ajax({
                type:'GET',
                url :"{% url 'ajson:getdata' %}",
                success: (response)=>{
                    //console.log(response)
                    $("#name-data").empty();
                    
                    for(key in response.profiles){
                        let temp = "<li>"+response.profiles[key].name +"</li><hr>"
                          $("#name-data").append(temp)
                    }
                        
                },
                error: (response)=>{
                    //alert(" erreur .....")
                }

            })
        },1000)
    })
</script>

{% endblock script %}
      

ajson/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>json ajax</title>
    
    {% block style %}
        
    {% endblock style %}
        
</head>
<body>
    
    {% block content %}
        
    {% endblock content %}
        
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    
    {% block script %}
        
    {% endblock script %}   
</body>
</html>